service: severless-appsync-lab

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
          Resource: "*"
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-appsync-simulator
  - serverless-appsync-plugin

functions:
  addTwoNumbers-fn:
    handler: src/handlers/addTwoNumbers/index.handler
  hello-fn:
    handler: src/handlers/helloFn/index.handler
  query-fn:
    handler: src/handlers/graphql/query/index.handler
  mutation-fn:
    handler: src/handlers/graphql/mutation/index.handler

custom:
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      # Uncomment only if you already have a DynamoDB running locally
      noStart: true
  appSync:
    name: ServerlessAppSyncImmersion
    schema: schema.graphql
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      defaultAction: ALLOW
      userPoolId: ap-southeast-1_z3Ef0wdx1
    mappingTemplatesLocation: src/mapping-templates

    mappingTemplates:
      - dataSource: DynamoDBColorTableDS
        type: Query
        field: colors
        request: Query.colors.request.vtl
        response: Query.colors.response.vtl
      - dataSource: DynamoDBColorTableDS
        type: Mutation
        field: addColor
        request: Mutation.addColor.request.vtl
        response: Mutation.addColor.response.vtl
      - dataSource: LambdaAddTwoNumbersDS
        type: Mutation
        field: addTwoNumbers
        request: false
        response: false
      - dataSource: LambdaHelloDS
        type: Query
        field: hello
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: company
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: companyCreate
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: user
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: userCreate
        request: false
        response: false

    dataSources:
      - type: AWS_LAMBDA
        name: LambdaAddTwoNumbersDS
        config:
          functionName: addTwoNumbers-fn
      - type: AMAZON_DYNAMODB
        name: DynamoDBColorTableDS
        config:
          tableName: !Ref ColorTable
      - type: AWS_LAMBDA
        name: LambdaHelloDS
        config:
          functionName: hello-fn
      - type: AWS_LAMBDA
        name: LambdaQueryDS
        config:
          functionName: query-fn
      - type: AWS_LAMBDA
        name: LambdaMutationDS
        config:
          functionName: mutation-fn

resources: # CloudFormation template syntax
  - ${file(./resources.yml)}
