service: severless-appsync-lab
# frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:BatchGetItem"
            - "dynamodb:BatchWriteItem"
            - "cognito-idp:AdminCreateUser"
            - "cognito-idp:AdminAddUserToGroup"
            - "cognito-idp:AdminRemoveUserFromGroup"
            - "cognito-idp:AdminUpdateUserAttributes"
            - "cognito-idp:AdminGetUser"
          Resource: "*"
plugins:
  - serverless-dynamodb-local
  - serverless-appsync-simulator
  - serverless-offline
  - serverless-appsync-plugin
  - serverless-webpack

useDotenv: true

functions:
  query-fn:
    handler: src/functions/graphql/query/index.handler
  mutation-fn:
    handler: src/functions/graphql/mutation/index.handler
  file-fn:
    handler: src/functions/graphql/file/index.handler
  company-fn:
    handler: src/functions/graphql/company/index.handler
  clientmatter-fn:
    handler: src/functions/graphql/clientMatter/index.handler
  background-fn:
    handler: src/functions/graphql/background/index.handler
  label-fn:
    handler: src/functions/graphql/label/index.handler
  brief-fn:
    handler: src/functions/graphql/brief/index.handler
  rfi-fn:
    handler: src/functions/graphql/rfi/index.handler
  user-fn:
    handler: src/functions/graphql/user/index.handler
  gmailmessage-fn:
    handler: src/functions/graphql/gmailMessage/index.handler
  gmail-re-subsription-fn:
    handler: src/functions/event-bridge/gmail-re-subscription/index.handler
    events:
      - schedule: rate(1 minute)
  gmail-watch-webhook-fn:
    handler: src/services/gmail/pushSubscription.pushSubscriptionHandler
    url: true

custom:
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      # Uncomment only if you already have a DynamoDB running locally
      noStart: true
  appSync:
    name: ServerlessAppSyncImmersion
    schema: schema.graphql
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      defaultAction: ALLOW
      userPoolId: !Ref CognitoUserPool
    mappingTemplatesLocation: src/mapping-templates

    mappingTemplates:
      # Company
      - dataSource: LambdaQueryDS
        type: Query
        field: company
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: companies
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: companyCreate
        request: false
        response: false
      # User Access
      - dataSource: LambdaQueryDS
        type: Query
        field: companyAccessType
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: companyAccessTypeCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: companyAccessTypeUpdate
        request: false
        response: false
      # User
      - dataSource: LambdaQueryDS
        type: Query
        field: user
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: users
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: userCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: userInvite
        request: false
        response: false
      - dataSource: LambdaUserDS
        type: User
        field: clientMatters
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: userColumnSettings
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: userColumnSettingsCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: userColumnSettingsUpdate
        request: false
        response: false
      - dataSource: LambdaCompanyDS
        type: Company
        field: users
        request: false
        response: false
      # Page
      - dataSource: LambdaQueryDS
        type: Query
        field: page
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: pages
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: pageCreate
        request: false
        response: false
      # Feature
      - dataSource: LambdaQueryDS
        type: Query
        field: feature
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: features
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: featureCreate
        request: false
        response: false
      # Matter File
      - dataSource: LambdaQueryDS
        type: Query
        field: matterFiles
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: matterFileCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: matterFileUpdate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: matterFileBulkUpdateOrders
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: matterFileSoftDelete
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: matterFileBulkSoftDelete
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: matterFileBulkCreate
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: file
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: files
        request: false
        response: false
      - dataSource: LambdaLabelDS
        type: Label
        field: files
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: fileLabelTag
        request: false
        response: false
      - dataSource: LambdaFileDS
        type: File
        field: downloadURL
        request: false
        response: false
      # RFI
      - dataSource: LambdaQueryDS
        type: Query
        field: rfi
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: rfis
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: rfiCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: rfiUpdate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: rfiDelete
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: rfiSoftDelete
        request: false
        response: false
      # Requests
      - dataSource: LambdaQueryDS
        type: Query
        field: request
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: requests
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: requestCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: requestUpdate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: requestDelete
        request: false
        response: false
      - dataSource: LambdaRFIDS
        type: RFI
        field: requests
        request: false
        response: false
      - dataSource: LambdaClientMatterDS
        type: ClientMatter
        field: rfis
        request: false
        response: false
      # Label
      - dataSource: LambdaFileDS
        type: File
        field: labels
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: label
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: labels
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: multipleLabels
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: labelCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: labelBulkCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: labelUpdate
        request: false
        response: false
      - dataSource: LambdaClientMatterDS
        type: ClientMatter
        field: labels
        request: false
        response: false
      # Client
      - dataSource: LambdaQueryDS
        type: Query
        field: clients
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: clientCreate
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: client
        request: false
        response: false
      - dataSource: LambdaCompanyDS
        type: Company
        field: clients
        request: false
        response: false
      # Client Matter
      - dataSource: LambdaMutationDS
        type: Mutation
        field: clientMatterCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: clientMatterDelete
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: clientMatter
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: clientMatters
        request: false
        response: false
      - dataSource: LambdaCompanyDS
        type: Company
        field: clientMatters
        request: false
        response: false
      # Matter
      - dataSource: LambdaMutationDS
        type: Mutation
        field: matterCreate
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: matter
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: matters
        request: false
        response: false
      - dataSource: LambdaCompanyDS
        type: Company
        field: matters
        request: false
        response: false
      # Brief
      - dataSource: LambdaQueryDS
        type: Query
        field: brief
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: briefs
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: briefCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: briefUpdate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: briefDelete
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: briefSoftDelete
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: briefBackgroundTag
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: briefBackgroundUntag
        request: false
        response: false
      - dataSource: LambdaClientMatterDS
        type: ClientMatter
        field: briefs
        request: false
        response: false
      # Background
      - dataSource: LambdaQueryDS
        type: Query
        field: background
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: backgrounds
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: backgroundCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: backgroundBulkCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: backgroundUpdate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: backgroundBulkUpdateOrders
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: backgroundDelete
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: backgroundBulkDelete
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: backgroundFileTag
        request: false
        response: false
      - dataSource: LambdaFileDS
        type: File
        field: backgrounds
        request: false
        response: false
      - dataSource: LambdaBackgroundDS
        type: Background
        field: files
        request: false
        response: false
      - dataSource: LambdaBackgroundDS
        type: Background
        field: briefs
        request: false
        response: false
      - dataSource: LambdaClientMatterDS
        type: ClientMatter
        field: backgrounds
        request: false
        response: false
      - dataSource: LambdaBriefDS
        type: Brief
        field: backgrounds
        request: false
        response: false
      # Column Settings
      - dataSource: LambdaQueryDS
        type: Query
        field: columnSettings
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: columnSettingsCreate
        request: false
        response: false
      # Gmail Messages
      - dataSource: LambdaQueryDS
        type: Query
        field: gmailMessages
        request: false
        response: false
      - dataSource: LambdaQueryDS
        type: Query
        field: gmailMessage
        request: false
        response: false
      - dataSource: LambdaCompanyDS
        type: Company
        field: gmailMessages
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: gmailMessageCreate
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: gmailMessageSave
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: gmailMessageSoftDelete
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: gmailMessageBulkSoftDelete
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: gmailMessageClientMatterTag
        request: false
        response: false
      - dataSource: LambdaGmailMessageDS
        type: GmailMessage
        field: clientMatters
        request: false
        response: false
      - dataSource: LambdaMutationDS
        type: Mutation
        field: gmailConnectFromCode
        request: false
        response: false

    # Data Sources
    dataSources:
      - type: AWS_LAMBDA
        name: LambdaQueryDS
        config:
          functionName: query-fn
      - type: AWS_LAMBDA
        name: LambdaMutationDS
        config:
          functionName: mutation-fn
      - type: AWS_LAMBDA
        name: LambdaBackgroundDS
        config:
          functionName: background-fn
      - type: AWS_LAMBDA
        name: LambdaBriefDS
        config:
          functionName: brief-fn
      - type: AWS_LAMBDA
        name: LambdaCompanyDS
        config:
          functionName: company-fn
      - type: AWS_LAMBDA
        name: LambdaClientMatterDS
        config:
          functionName: clientmatter-fn
      - type: AWS_LAMBDA
        name: LambdaFileDS
        config:
          functionName: file-fn
      - type: AWS_LAMBDA
        name: LambdaLabelDS
        config:
          functionName: label-fn
      - type: AMAZON_DYNAMODB
        name: DynamoDBMatterFileTableDS
        config:
          tableName: !Ref MatterFileTable
      - type: AWS_LAMBDA
        name: LambdaRFIDS
        config:
          functionName: rfi-fn
      - type: AWS_LAMBDA
        name: LambdaUserDS
        config:
          functionName: user-fn
      - type: AWS_LAMBDA
        name: LambdaGmailMessageDS
        config:
          functionName: gmailmessage-fn

resources: # CloudFormation template syntax
  - ${file(./resources.yml)}
