export const AppRoutes = {
  DASHBOARD: "/dashboard",
  MATTERSOVERVIEW: "/matters-overview",
  WITNESSAFFIDAVIT: "/witness-affidavit",
  MATTERSRFI: "/matters-rfi",
  USERTYPEACCESS: "/usertype-access",
  CONTACTS: "/contacts",
  ACCOUNTSETTINGS: "/account-settings",
  POSTREGISTRATION: "/post-registration",
  POSTAUTHENTICATION: "/post-authentication",
  SIGNOUT: "/signout",
  FILEBUCKET: "/file-bucket",
  BACKGROUND: "/background",
  INBOX: "/inbox",
};
