/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:e4457518-f974-4dca-9060-36f32dbe37f4",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_eG5B1KoPb",
    "aws_user_pools_web_client_id": "1snvd8fhkisj0ab2lib41sbse9",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "mmastorageapp-staging",
    "aws_user_files_s3_bucket_region": "ap-southeast-1",
    //"aws_appsync_graphqlEndpoint": "https://wiy5ozkk4fda7ofpno2snytr6y.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_graphqlEndpoint": process.env.NODE_ENV === "development" ? process.env.REACT_APP_LOCAL_GRAPHQL_ENDPOINT : process.env.REACT_APP_GRAPHQL_ENDPOINT,
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
