export const inbox = [
  {
    id: 1,
    firstname: "Joseph",
    lastname: "Aguilar",
    title: "FWD: New Project 3 {new-0101001010}",
    date: "2022-04-23T18:25:43.511Z",
    status: "unread",
    email: "joseph.aguilar@lophils.com",
    tags: [
      { name: "New Project 4" },
      { name: "New Project 3" },
      { name: "Project 8" },
      { name: "New Project 4" },
    ],
    message: "Hello i have finish background page",
    save: false,
  },
  {
    id: 2,
    firstname: "Joseph",
    lastname: "Aguilar",
    title: "FWD: New Project 3 {new-0101001010}",
    date: "2022-04-23T18:25:43.511Z",
    status: "unread",
    email: "joseph.aguilar@lophils.com",
    tags: [
      { name: "New Project 4" },
      { name: "New Project 3" },
      { name: "Project 8" },
      { name: "New Project 4" },
    ],
    message: "Hello i have finish background page",
    save: false,
  },
  {
    id: 3,
    firstname: "Joseph",
    lastname: "Aguilar",
    title: "FWD: New Project 3 {new-0101001010}",
    date: "2022-04-23T18:25:43.511Z",
    status: "unread",
    email: "joseph.aguilar@lophils.com",
    tags: [
      { name: "New Project 4" },
      { name: "New Project 3" },
      { name: "Project 8" },
      { name: "New Project 4" },
    ],
    message: "Hello i have finish background page",
    attachments: [
      {
        pdf: "hr_attachment.pdf",
      },
      {
        pdf: "hr_attachment.pdf",
      },
      {
        pdf: "hr_attachment.pdf",
      },
    ],
    save: true,
  },
  {
    id: 4,
    firstname: "Joseph",
    lastname: "Aguilar",
    title: "FWD: New Project 3 {new-0101001010}",
    date: "2022-04-23T18:25:43.511Z",
    status: "read",
    email: "joseph.aguilar@lophils.com",
    tags: [
      { name: "New Project 4" },
      { name: "New Project 3" },
      { name: "Project 8" },
      { name: "New Project 4" },
    ],
    message: "Hello i have finish background page",
    save: true,
  },
  {
    id: 5,
    firstname: "Joseph",
    lastname: "Aguilar",
    title: "FWD: New Project 3 {new-0101001010}",
    date: "2022-04-23T18:25:43.511Z",
    status: "read",
    email: "joseph.aguilar@lophils.com",
    tags: [
      { name: "New Project 4" },
      { name: "New Project 3" },
      { name: "Project 8" },
      { name: "New Project 4" },
    ],
    message: "Hello i have finish background page",
    save: true,
  },
  {
    id: 6,
    firstname: "Joseph",
    lastname: "Aguilar",
    title: "FWD: New Project 3 {new-0101001010}",
    date: "2022-04-23T18:25:43.511Z",
    status: "read",
    email: "joseph.aguilar@lophils.com",
    tags: [
      { name: "New Project 4" },
      { name: "New Project 3" },
      { name: "Project 8" },
      { name: "New Project 4" },
    ],
    message: "Hello i have finish background page",
    save: false,
  },
  {
    id: 7,
    firstname: "Joseph",
    lastname: "Aguilar",
    title: "FWD: New Project 3 {new-0101001010}",
    date: "2022-04-23T18:25:43.511Z",
    status: "read",
    email: "joseph.aguilar@lophils.com",
    tags: [
      { name: "New Project 4" },
      { name: "New Project 3" },
      { name: "Project 8" },
      { name: "New Project 4" },
    ],
    message: "Hello i have finish background page",
    save: false,
  },
];
